# Generated by Django 5.2.9 on 2026-03-30 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('github_url', models.URLField(blank=True)),
                ('api_base_url', models.URLField(blank=True)),
                ('api_list', models.TextField(blank=True, default='')),
                ('stack_name', models.CharField(blank=True, max_length=120)),
                ('subdomains', models.TextField(blank=True, default='')),
                ('test_email', models.EmailField(blank=True, max_length=254)),
                ('encrypted_test_password', models.TextField(blank=True)),
                ('masked_token', models.CharField(blank=True, max_length=255)),
                ('encrypted_token', models.TextField(blank=True)),
                ('scan_enabled', models.BooleanField(default=False)),
                ('scan_frequency', models.CharField(choices=[('manual', 'Manual'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='manual', max_length=20)),
                ('notification_email', models.EmailField(blank=True, max_length=254)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('next_scan_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
                'unique_together': {('user', 'name')},
            },
        ),
    ]
