# Generated by Django 5.2.9 on 2026-03-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='scan_mode',
            field=models.CharField(choices=[('basic', 'Basic'), ('advanced', 'Advanced')], default='advanced', max_length=20),
        ),
    ]
