# Generated by Django 5.2.9 on 2026-03-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_scan_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='backend_github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='frontend_github_url',
            field=models.URLField(blank=True),
        ),
    ]
