# Generated by Django 5.2.9 on 2026-03-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_backend_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='encrypted_server_password',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='server_ip_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='scan_mode',
            field=models.CharField(choices=[('basic', 'Basic'), ('advanced', 'Advanced'), ('server', 'Server')], default='advanced', max_length=20),
        ),
    ]
