# Generated by Django 5.2.9 on 2026-03-30 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_project_scan_mode'),
        ('scans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=255)),
                ('normalized_domain', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('https_status', models.IntegerField(blank=True, null=True)),
                ('final_url', models.URLField(blank=True, max_length=500)),
                ('ssl_grade', models.CharField(blank=True, max_length=20)),
                ('certificate_issuer', models.CharField(blank=True, max_length=255)),
                ('certificate_expiry', models.DateTimeField(blank=True, null=True)),
                ('days_to_expiry', models.IntegerField(blank=True, null=True)),
                ('dns_json', models.JSONField(blank=True, default=dict)),
                ('headers_json', models.JSONField(blank=True, default=dict)),
                ('subdomains_json', models.JSONField(blank=True, default=dict)),
                ('public_files_json', models.JSONField(blank=True, default=dict)),
                ('risk_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_provider', models.CharField(blank=True, max_length=50)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_scans', to='projects.project')),
                ('scan_result', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surface_scan', to='scans.scanresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='DomainFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], max_length=20)),
                ('key', models.CharField(max_length=120)),
                ('value', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('recommendation', models.TextField(blank=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='surface_scan.domainscan')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
