# Generated by Django 5.2.9 on 2026-03-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surface_scan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainfinding',
            name='confidence',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='domainfinding',
            name='evidence_source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='domainfinding',
            name='expected_value',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='domainfinding',
            name='module_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='domainfinding',
            name='observed_value',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='domainscan',
            name='ct_status_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='domainscan',
            name='dns_status_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='domainscan',
            name='email_security_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='domainscan',
            name='fingerprint_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='domainscan',
            name='public_file_validation_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='domainscan',
            name='redirect_chain_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='domainscan',
            name='timing_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='domainscan',
            name='tls_status_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
